// main.c - main function of the kernel (called from start.s)
//
// Copyright (c) 2024-2026 University of Illinois
// SPDX-License-identifier: NCSA
//

#include "../../conf.h"
#include "../../console.h"
#include "../../intr.h"
#include "../../plic.h"
#include "../../device.h"
#include "../../thread.h"
#include "../../timer.h"
#include "../../string.h"
#include "../../error.h"
#include "../../misc.h" // for halt()
#include "../../heap.h"
#include "../../io.h"
#include "../../fs/ngfs.h"
#include "../../fs/ktfs.h"
#include "../../fs/tarfs.h"
#include "../../filesys.h"
#include "../../process.h"
#include "tests.c"

#ifndef MP2
#define INITEXE "shell"

#define CMNTNAME "c" // ngfs
#define DMNTNAME "d" // ktfs
#define DEVMNTNAME "dev"
#define CDEVNAME "vioblk1"
#define DDEVNAME "vioblk0"

#ifndef NUART // number of UARTs
#define NUART 3
#endif
#endif

static void exec_init();
static void mount_drive(char * mntname, char * devname,
		int (*mount)(const char * mpname, struct io * bkgio));

extern void board_init(unsigned int hartid, void * dtb); // from board/xxx.c
extern void attach_devices(void); // from board/xxx.c

void main(unsigned int hartid, void * dtb) {
	board_init(hartid, dtb);
	intrmgr_init();
	devmgr_init();
	thrmgr_init();

	// MP3 stuff
	memory_init();
	procmgr_init();
	fsmgr_init();

	attach_devices();
	enable_interrupts();

	mount_devfs(DEVMNTNAME);
	mount_drive(CMNTNAME, CDEVNAME, mount_ngfs);
	mount_drive(DMNTNAME, DDEVNAME, mount_ktfs);
	exec_init();
}

void mount_drive(char * mntname, char * devname, 
		int (*mount)(const char * mpname, struct io * bkgio)) {

	struct io * hd;
	int result;

	result = open_device(devname, &hd);

	if (result < 0) {
		kprintf("Failed to open storage device %s: %s\n", 
				devname, error_desc(result));
		halt();
	}

	result = mount(mntname, hd);

	if (result != 0) {
		kprintf("mount(%s, bkgio(%s)) failed: %s\n",
				mntname, devname, error_desc(result));
		halt();
	}
}

#ifndef HEAP_INIT_MIN
#define HEAP_INIT_MIN 256
#endif

void exec_init() {
	extern char _kimg_end[];  // provided by kernel.ld
	int fail = 0;
	int total = 0;

	struct io* uart;
	open_device("uart0", &uart);

	test_control_y(uart, &fail, &total);
	test_control_n(uart, &fail, &total);

	if(fail > 0){
		kprintf("WARN: User input tests failed\n");
	}

	//This is a hacky way to retrieve the chunk list.
	struct page_chunk** chunklist_ptr = (void*)0x8009c680; //Generated by checking address of free_chunk_list via gdb.
	unsigned long max_free = test_init(*chunklist_ptr, &fail, &total);

	if(max_free <= 0){
		kprintf("WARN: Found no pages to map\n");
	}

	kprintf("\n----BEGIN ALLOCATOR TESTS----\n- alloc_phys_pages\n- alloc_phys_page\n- free_phys_pages\n- free_phys_page\n- free_phys_page_count\n----         ~*~         ----\n");

	void* blk = test_alloc_1_simple(*chunklist_ptr, max_free, &fail, &total);
	test_free_simple(blk, max_free, &fail, &total);

	kprintf("\nChecking for coalescing...\n");
	int will_coalesce = cmp_chunk_size(*chunklist_ptr, max_free*PAGE_SIZE) == 0;

	if(will_coalesce)
		kprintf("Detected Coalescing Allocator.\n\n");
	else
		kprintf("Coalescing NOT Detected.\n\n");

	blk = test_alloc_4(*chunklist_ptr, max_free, &fail, &total);
	test_free_4(blk, max_free, &fail, &total);
	test_best_fit(*chunklist_ptr, &fail, &total);

	kprintf("---- END ALLOCATOR TESTS ----\n");

	map_usr_simple(uart, (void*)0xc0001000, &fail, &total);
	clear_x_simple(uart, (void*)0xc0001000, &fail, &total);
	read_write_mapped_page((void*)0xc0001000, &fail, &total);
	
	int fails = fail;
	s_mode_faulter((void*)0xc0000000, &fail, &total);
	if(fails == fail){
		//The validation tests need you to be able to write arbitrary user memory
		//So we just skip them if the S mode faulter fails
		//Though the S mode faulter usually fails fatally so...
		test_validation(&fail, &total);
	}

	test_reset(uart, max_free, &fail, &total);
	mtag_t new_mtag = test_clone(&fail, &total);
	test_discard(new_mtag, max_free-3, &fail, &total); //lv 2, lv 1, lv 0 page for new global entry = 3
	
	if(fails != fail){
		kprintf("WARN: Detected failing essential functionality. Skipping all to end.\n");
		goto end_test;
	}

	//These tests need to be able to write arbitrary memory and reset.
	//Luckily, they don't care about fragmentation.	
	if(wait_for_user_input(uart, "yYnN", "Skip Long Tests? Y/N\n")/2){
		complete_memtest((uintptr_t)0xc0001000, &fail, &total);
	}

end_test:
	kprintf("Test Complete!\n");
	kprintf("%d PASSES, %d FAILS out of %d TOTAL\n", total - fail, fail, total);
}

